import { defineConfig } from 'vitest/config'
import react from '@vitejs/plugin-react'
import pkg from './package.json'

/**
 * Vitest configuration optimized for CI environments (Regular Shards)
 *
 * Key optimizations:
 * - pool: 'forks' - isolates each test file in separate process, prevents memory accumulation
 * - isolate: true - ensures complete isolation between tests
 * - maxConcurrency: 2 - limits parallel tests to reduce memory pressure
 * - Reduced reporter verbosity for faster output
 * - Coverage enabled via --coverage flag (Story 14.30.1)
 * - Heavy test files excluded (run in dedicated jobs via vitest.config.heavy.ts)
 *
 * Used by:
 * - CI unit test shards (test-unit-1 through test-unit-5)
 * - Each shard collects coverage, merged in merge-coverage job
 *
 * Heavy tests (excluded, run separately):
 * - tests/unit/hooks/useScanStateMachine.test.ts (1680 lines)
 * - tests/unit/components/Nav.test.tsx (1623 lines)
 * - tests/unit/services/insightEngineService.test.ts (1439 lines)
 * - tests/unit/utils/insightGenerators.test.ts (1432 lines)
 *
 * @see vitest.config.heavy.ts for heavy test configuration
 * @see Story 14.30.6: Heavy test isolation
 */
export default defineConfig({
  plugins: [react()],
  // Define global constants (same as vite.config.ts)
  define: {
    __APP_VERSION__: JSON.stringify(pkg.version),
  },
  test: {
    globals: true,
    environment: 'happy-dom',
    setupFiles: './tests/setup/vitest.setup.ts',
    include: ['tests/unit/**/*.test.{ts,tsx}'],
    exclude: [
      '**/node_modules/**',
      '**/dist/**',
      // Heavy test files - run in dedicated jobs (vitest.config.heavy.ts)
      // Tier 1: 1400-1700 lines each (original 4)
      'tests/unit/hooks/useScanStateMachine.test.ts',
      'tests/unit/components/Nav.test.tsx',
      'tests/unit/services/insightEngineService.test.ts',
      'tests/unit/utils/insightGenerators.test.ts',
      // Tier 2: 800-1100 lines each (additional 6)
      'tests/unit/csvExport.test.ts',
      'tests/unit/analytics/DrillDownCard.test.tsx',
      'tests/unit/analytics/DrillDownGrid.test.tsx',
      'tests/unit/components/session/SessionComplete.test.tsx',
      'tests/unit/services/pendingScanStorage.test.ts',
      'tests/unit/analytics/CategoryBreadcrumb.test.tsx',
    ],
    // Use forks pool to isolate each test file - prevents memory leaks
    pool: 'forks',
    poolOptions: {
      forks: {
        // Limit concurrent forks to reduce memory pressure (GitHub runners have 7GB RAM)
        maxForks: 2,
        minForks: 1,
        // Isolate each test file to prevent memory accumulation
        isolate: true,
      },
    },
    // Limit concurrent test files
    maxConcurrency: 2,
    // Reduced reporter for faster CI output (default is verbose)
    reporters: ['default'],
    // Disable watch mode for CI
    watch: false,
    // Coverage configuration (activated with --coverage flag)
    coverage: {
      provider: 'v8',
      reporter: ['json'],  // Only JSON for merging; HTML generated by merge job
      reportsDirectory: './coverage',
      include: ['src/**/*.{ts,tsx}'],
      exclude: [
        'src/**/*.d.ts',
        'src/**/*.test.{ts,tsx}',
        'src/vite-env.d.ts',
      ],
    },
  },
})
