export {
  type ImageProcessingStatus,
  type ImageProcessingState,
  type ProcessingResult,
  type StatusCallback,
  type ProgressCallback,
  type BatchProcessingOptions,
  processImagesInParallel,
  retryImage,
  calculateTotalProcessingTime,
  getBatchSummary,
  isBatchComplete,
  getSuccessfulTransactions,
  getFailedStates,
} from './batchProcessingService';
