# ECC-Enhanced Story Development Workflow
name: ecc-dev-story
description: "Story implementation using ECC agents with TDD-first development and parallel reviews"
author: "BMad"

# ECC Integration - Orchestrator Configuration
ecc_orchestration:
  enabled: true
  orchestrator: "ECC Orchestrator"

  # ECC agents used in this workflow
  agents:
    planner:
      subagent_type: "everything-claude-code:planner"
      model: "opus"
      max_turns: 7
      purpose: "Implementation planning and risk assessment"
    tdd-guide:
      subagent_type: "everything-claude-code:tdd-guide"
      model: "opus"
      # No max_turns — iterative implementation needs many turns
      purpose: "Test-driven development, RED-GREEN-REFACTOR cycle"
    build-error-resolver:
      subagent_type: "everything-claude-code:build-error-resolver"
      model: "sonnet"
      max_turns: 5
      purpose: "Fix build/TypeScript errors with minimal diffs"
    code-reviewer:
      subagent_type: "everything-claude-code:code-reviewer"
      model: "sonnet"
      max_turns: 7
      purpose: "Code quality self-review before completion"

  # Workflow sequence
  sequence: "planner -> tdd-guide -> build-error-resolver (on failure) -> code-reviewer"

  # Pre-completion review (code-reviewer only — formal review is via /ecc-code-review)
  pre_completion_review:
    agents: ["code-reviewer"]
    description: "Quick self-review before marking story review-ready"

# Project Knowledge Integration (replaces Atlas - migrated 2026-02-05)
project_knowledge:
  enabled: true
  load_at_session_start: true
  files:
    required:
      - "{project-root}/_ecc/knowledge/code-review-patterns.md"
      - "{project-root}/.claude/rules/testing.md"
      - "{project-root}/docs/architecture/firestore-patterns.md"
    optional:
      - "{project-root}/docs/architecture/state-management.md"
      - "{project-root}/docs/architecture/component-patterns.md"
      - "{project-root}/_bmad/tea/testarch/knowledge/playwright-cli.md"  # TEA: browser automation CLI reference

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
date: system-generated

sprint_artifacts: "{project-root}/docs/sprint-artifacts"
story_dir: "{sprint_artifacts}/stories"
story_file: ""
context_file: "{story_dir}/{{story_key}}.context.xml"
sprint_status: "{sprint_artifacts}/sprint-status.yaml"

# Project knowledge paths (replaces Atlas memory - migrated 2026-02-05)
project_knowledge_path: "{project-root}/_ecc/knowledge"
project_architecture_path: "{project-root}/docs/architecture"

# Workflow components
installed_path: "{project-root}/_ecc/workflows/ecc-dev-story"
instructions: "{installed_path}/instructions.xml"

# Workflow Optimizations (see docs/architecture/plans/ECC-WORKFLOW-OPTIMIZATIONS.md)
workflow_optimizations:
  tdd:
    run_per_edit: true            # Run tests per-edit with npx vitest run <path>
    avoid_full_suite: true        # Don't run full suite per subtask
  validation:
    consolidate_builds: true
    skip_type_check_if_build_passes: true
  progress_tracking:
    mode: "batched"  # Options: immediate | batched | minimal
    batch_at:
      - task_complete     # Batch all subtask checkboxes into single story edit
      - story_complete    # Update sprint-status.yaml only at story end
  knowledge:
    cache_at_session_start: true
    summarize_for_story_type: true
    cache_files:
      - "_ecc/knowledge/code-review-patterns.md"
      - ".claude/rules/testing.md"
      - "docs/architecture/firestore-patterns.md"
      - "docs/architecture/state-management.md"
      - "docs/architecture/component-patterns.md"

# Branch Guard Configuration
branch_guard:
  enabled: true
  protected_branches: ["main", "develop"]
  branch_from: "develop"
  naming_convention: "feature/{{story_key}}"
  sync_check: true          # Verify branch is up-to-date with develop
  auto_create: true          # Offer to create feature branch if on protected branch
  stash_uncommitted: true    # Stash changes before switching branches

# Mid-Story Sizing Configuration (see docs/architecture/plans/ECC-MID-STORY-SIZING-PLAN.md)
mid_story_sizing:
  enabled: true
  post_planning_check: true     # Step 2.5: Check after planning
  per_task_check: true          # Step 4 loop: Check after each task
  pre_review_check: false       # Removed — sizing validated per-task in Step 4
  auto_suggest_split: true      # Suggest split when thresholds exceeded
  block_on_exceed: false        # Warning only — user always has control
  record_metrics: true          # Save metrics in Dev Notes

  # Thresholds
  thresholds:
    small:
      max_tasks: 2
      max_subtasks: 5
      max_files: 2
    medium:
      max_tasks: 3
      max_subtasks: 10
      max_files: 4
    large:
      max_tasks: 4
      max_subtasks: 15
      max_files: 8
    too_large:
      description: "REQUIRES SPLIT"
      trigger: ">4 tasks OR >15 subtasks OR >8 files"

  # Growth alert thresholds
  growth_alerts:
    file_growth: 3        # Alert if files exceed original estimate by 3+
    subtask_growth: 5     # Alert if subtasks exceed original by 5+
    loc_per_task: 500     # Alert if LOC exceeds 500 per task

standalone: true
