# ECC-Enhanced Story Development Workflow
name: ecc-dev-story
description: "Story implementation using ECC agents orchestrated by Atlas Puppeteer - TDD-first development with parallel reviews"
author: "BMad + Atlas Puppeteer"

# ECC Integration - Atlas as Puppeteer Orchestrator
ecc_orchestration:
  enabled: true
  orchestrator: "Atlas Puppeteer"

  # ECC agents used in this workflow
  agents:
    planner:
      subagent_type: "everything-claude-code:planner"
      purpose: "Implementation planning and risk assessment"
    tdd_guide:
      subagent_type: "everything-claude-code:tdd-guide"
      purpose: "Test-driven development, RED-GREEN-REFACTOR cycle"
    build_resolver:
      subagent_type: "everything-claude-code:build-error-resolver"
      purpose: "Fix build/TypeScript errors with minimal diffs"
    code_reviewer:
      subagent_type: "everything-claude-code:code-reviewer"
      purpose: "Code quality self-review before completion"
    security_reviewer:
      subagent_type: "everything-claude-code:security-reviewer"
      purpose: "Security analysis for sensitive code"

  # Workflow sequence
  sequence: "planner → tdd-guide → build-error-resolver (on failure) → code-reviewer"

  # Parallel phases
  parallel_phases:
    pre_completion_review:
      agents: ["code-reviewer", "security-reviewer"]
      description: "Parallel self-review before marking story complete"

# Atlas Integration
atlas_features:
  consult_architecture: true
  consult_testing: true
  consult_lessons: true
  workflow_chain_awareness: true
  memory_feeding: true
  puppeteer_orchestration: true  # NEW: Enable ECC orchestration

atlas_knowledge_fragments:
  required:
    - "04-architecture.md"
    - "05-testing.md"
    - "08-workflow-chains.md"
  optional:
    - "06-lessons.md"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
story_dir: "{config_source}:sprint_artifacts"
date: system-generated

story_file: ""
context_file: "{story_dir}/{{story_key}}.context.xml"
sprint_artifacts: "{config_source}:sprint_artifacts"
sprint_status: "{sprint_artifacts}/sprint-status.yaml || {output_folder}/sprint-status.yaml"

# Atlas memory paths
atlas_memory: "{project-root}/_bmad/agents/atlas/atlas-sidecar"
atlas_index: "{atlas_memory}/atlas-index.csv"
atlas_knowledge: "{atlas_memory}/knowledge"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/ecc-dev-story"
instructions: "{installed_path}/instructions.xml"
validation: "{installed_path}/checklist.md"

standalone: true
