# Test Architect workflow: chrome-e2e
name: testarch-chrome-e2e
description: "Interactive E2E testing using Claude Code CLI with Chrome MCP tools - visual inspection, DevTools integration, and real browser automation"
author: "BMad"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
date: system-generated

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/testarch/chrome-e2e"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Variables and inputs
variables:
  test_dir: "{project-root}/tests" # Root test directory
  e2e_dir: "{project-root}/tests/e2e" # E2E test directory
  base_url: "http://localhost:5173" # Default Vite dev server

# Output configuration
default_output_file: "{output_folder}/chrome-e2e-session-{date}.md"

# Required tools - Claude Code CLI Chrome MCP tools
required_tools:
  # Chrome MCP tools (require CLI, not VS Code extension)
  - mcp__claude-in-chrome__navigate # Go to URLs
  - mcp__claude-in-chrome__computer # Screenshots, clicks, typing
  - mcp__claude-in-chrome__tabs_context_mcp # Manage browser tabs
  - mcp__claude-in-chrome__execute_js # Execute JavaScript in page context
  - mcp__claude-in-chrome__evaluate # Evaluate expressions
  # Standard tools
  - read_file # Read test files, configs
  - write_file # Create test files, reports
  - bash # Run dev server, test commands

# Environment requirements
environment_requirements:
  - "Claude Code CLI (not VS Code extension)"
  - "Chrome browser running in WSL"
  - "Claude in Chrome extension installed"
  - "/chrome command shows 'Extension: Installed'"

tags:
  - qa
  - e2e
  - chrome
  - visual-testing
  - devtools
  - interactive
  - wsl

execution_hints:
  interactive: true # Highly interactive workflow
  autonomous: false # Requires user observation and decisions
  iterative: true
  cli_only: true # Does NOT work in VS Code extension
