# ECC-Enhanced Code Review Workflow
name: ecc-code-review
description: "Parallel multi-agent code review using ECC agents with adaptive classification"
author: "BMad"

# ECC Integration - Orchestrator Configuration
ecc_orchestration:
  enabled: true
  orchestrator: "ECC Orchestrator"

  # ECC agents used in this workflow (ALL RUN IN PARALLEL)
  agents:
    code-reviewer:
      subagent_type: "everything-claude-code:code-reviewer"
      purpose: "Code quality, maintainability, best practices"
    security-reviewer:
      subagent_type: "everything-claude-code:security-reviewer"
      purpose: "OWASP Top 10, secrets, vulnerabilities"
    architect:
      subagent_type: "everything-claude-code:architect"
      purpose: "Architecture compliance, patterns, design"
    tdd-guide:
      subagent_type: "everything-claude-code:tdd-guide"
      purpose: "Test coverage, TDD compliance, test quality"

  # Parallel execution - ALL agents spawn simultaneously
  parallel_execution: true
  sequence: "[code-reviewer + security-reviewer + architect + tdd-guide] parallel → Review synthesis"

# Project Knowledge Integration (replaces Atlas - migrated 2026-02-05)
project_knowledge:
  enabled: true
  load_at_session_start: true
  files:
    required:
      - "{project-root}/_ecc/knowledge/code-review-patterns.md"
      - "{project-root}/.claude/rules/testing.md"
      - "{project-root}/docs/architecture/firestore-patterns.md"
    optional:
      - "{project-root}/docs/architecture/state-management.md"
      - "{project-root}/docs/architecture/component-patterns.md"
      - "{project-root}/_bmad/tea/testarch/knowledge/test-quality.md"  # TEA: 5-dimension test quality scoring

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
date: system-generated

sprint_artifacts: "{project-root}/docs/sprint-artifacts"
sprint_status: "{sprint_artifacts}/sprint-status.yaml"

# Project knowledge paths (replaces Atlas memory - migrated 2026-02-05)
project_knowledge_path: "{project-root}/_ecc/knowledge"
project_architecture_path: "{project-root}/docs/architecture"

# Workflow components
installed_path: "{project-root}/_ecc/workflows/ecc-code-review"
instructions: "{installed_path}/instructions.xml"

# ECC Adaptive Review Configuration (see docs/architecture/plans/ECC-ADAPTIVE-REVIEW-PLAN.md)
adaptive_review:
  enabled: true

  # Classification thresholds
  thresholds:
    trivial:
      max_tasks: 1
      max_subtasks: 3
      max_files: 2
    simple:
      max_tasks: 3
      max_subtasks: 10
      max_files: 5
    standard:
      max_tasks: 4
      max_subtasks: 15
      max_files: 8
    complex:
      # Anything exceeding standard thresholds

  # Security-sensitive patterns (force-include security-reviewer)
  security_patterns:
    - "firestore.rules"
    - "**/security/**"
    - "**/functions/**"
    - "**/auth/**"

  # Architecture-sensitive patterns (force-include architect)
  architecture_patterns:
    - "**/stores/**"
    - "**/contexts/**"
    - "**/features/**/index.ts"
    - "**/*.types.ts"

  # Agent selection per classification
  agent_selection:
    trivial: ["code-reviewer"]
    simple: ["code-reviewer", "tdd-guide"]
    standard: ["code-reviewer", "security-reviewer"]
    complex: ["code-reviewer", "security-reviewer", "architect", "tdd-guide"]

  # Weighted scoring (base weights, redistributed for active agents)
  scoring_weights:
    code-reviewer: 40
    security-reviewer: 30
    architect: 20
    tdd-guide: 10

standalone: true
