/**
 * Tests for handlePrintReport() and generatePdfFilename()
 *
 * Story 15-TD-17: Replace innerHTML template literals with
 * createElement/textContent for defense-in-depth XSS prevention.
 * Story 15-TD-22: Extracted to printUtils.ts with i18n support.
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { handlePrintReport, generatePdfFilename } from '@/features/reports/utils/printUtils';

describe('handlePrintReport - DOM API sanitization', () => {
  let printContainer: HTMLDivElement;
  let reportContentDiv: HTMLDivElement;
  let reportContentRef: { current: HTMLDivElement | null };
  const mockPrint = vi.fn();
  let originalPrint: typeof window.print;
  let originalTitle: string;

  const baseReportData = {
    fullTitle: 'Semana 23 · Diciembre · Q4 2025',
    transactionCount: 42,
    periodType: 'weekly' as const,
    dateRange: {
      start: new Date(2025, 11, 2),
      end: new Date(2025, 11, 8),
    },
  };

  beforeEach(() => {
    // Setup DOM
    printContainer = document.createElement('div');
    printContainer.id = 'print-container';
    document.body.appendChild(printContainer);

    reportContentDiv = document.createElement('div');
    reportContentDiv.textContent = 'Report content';
    reportContentRef = { current: reportContentDiv };

    originalPrint = window.print;
    window.print = mockPrint;
    originalTitle = document.title;
  });

  afterEach(() => {
    printContainer.remove();
    window.print = originalPrint;
    document.title = originalTitle;
    mockPrint.mockClear();
    vi.restoreAllMocks();
  });

  it('should create branding section with DOM APIs', () => {
    handlePrintReport(reportContentRef, baseReportData, 'es');

    const branding = printContainer.querySelector('.print-branding');
    expect(branding).not.toBeNull();

    const logoCircle = branding?.querySelector('.print-logo-circle');
    expect(logoCircle).not.toBeNull();
    expect(logoCircle?.textContent).toBe('G');

    const wordmark = branding?.querySelector('.print-wordmark');
    expect(wordmark).not.toBeNull();
    expect(wordmark?.textContent).toBe('Gastify');
  });

  it('should create report header with textContent (not innerHTML)', () => {
    handlePrintReport(reportContentRef, baseReportData, 'es');

    const header = printContainer.querySelector('.print-report-header');
    expect(header).not.toBeNull();

    const h1 = header?.querySelector('h1');
    expect(h1).not.toBeNull();
    expect(h1?.textContent).toBe('Semana 23 · Diciembre · Q4 2025');

    const p = header?.querySelector('p');
    expect(p).not.toBeNull();
    expect(p?.textContent).toBe('42 transacciones');
  });

  it('should use singular "transacción" when count is 1', () => {
    handlePrintReport(reportContentRef, {
      ...baseReportData,
      transactionCount: 1,
    }, 'es');

    const header = printContainer.querySelector('.print-report-header');
    const p = header?.querySelector('p');
    expect(p?.textContent).toBe('1 transacción');
  });

  it('should create footer with i18n strings (es)', () => {
    handlePrintReport(reportContentRef, baseReportData, 'es');

    const footer = printContainer.querySelector('.print-footer');
    expect(footer).not.toBeNull();

    const divider = footer?.querySelector('.print-footer-divider');
    expect(divider).not.toBeNull();

    const title = footer?.querySelector('.print-footer-title');
    expect(title?.textContent).toBe('Reporte generado automáticamente por Gastify');

    const disclaimer = footer?.querySelector('.print-footer-disclaimer');
    expect(disclaimer?.textContent).toBe('Este reporte es solo para uso personal.');

    const url = footer?.querySelector('.print-footer-url');
    expect(url?.textContent).toBe('gastify.cl');
  });

  it('should default to Spanish when lang is omitted', () => {
    handlePrintReport(reportContentRef, baseReportData);

    const footer = printContainer.querySelector('.print-footer');
    const title = footer?.querySelector('.print-footer-title');
    expect(title?.textContent).toBe('Reporte generado automáticamente por Gastify');
  });

  it('should use English translations when lang is en', () => {
    handlePrintReport(reportContentRef, baseReportData, 'en');

    const footer = printContainer.querySelector('.print-footer');
    const title = footer?.querySelector('.print-footer-title');
    expect(title?.textContent).toBe('Report auto-generated by Gastify');

    const disclaimer = footer?.querySelector('.print-footer-disclaimer');
    expect(disclaimer?.textContent).toBe('This report is for personal use only.');

    const header = printContainer.querySelector('.print-report-header');
    const p = header?.querySelector('p');
    expect(p?.textContent).toBe('42 transactions');
  });

  it('should use singular "transaction" in English when count is 1', () => {
    handlePrintReport(reportContentRef, {
      ...baseReportData,
      transactionCount: 1,
    }, 'en');

    const header = printContainer.querySelector('.print-report-header');
    const p = header?.querySelector('p');
    expect(p?.textContent).toBe('1 transaction');
  });

  it('should escape XSS in fullTitle via textContent', () => {
    const xssData = {
      ...baseReportData,
      fullTitle: '<script>alert("xss")</script>',
    };

    handlePrintReport(reportContentRef, xssData, 'es');

    const h1 = printContainer.querySelector('.print-report-header h1');
    // textContent preserves the literal string — browser does NOT parse it as HTML
    expect(h1?.textContent).toBe('<script>alert("xss")</script>');
    // innerHTML shows the escaped version, proving it was set via textContent
    expect(h1?.innerHTML).toBe('&lt;script&gt;alert("xss")&lt;/script&gt;');
  });

  it('should do nothing when reportContentRef.current is null', () => {
    const nullRef = { current: null };
    handlePrintReport(nullRef, baseReportData, 'es');

    expect(mockPrint).not.toHaveBeenCalled();
  });

  it('should call window.print after populating container', () => {
    handlePrintReport(reportContentRef, baseReportData, 'es');

    expect(mockPrint).toHaveBeenCalledOnce();
  });

  it('should set document.title to generated filename', () => {
    handlePrintReport(reportContentRef, baseReportData, 'es');

    // Weekly report: Gastify_report_YYYY_Q4_Dic_SXX
    expect(document.title).toMatch(/^Gastify_report_2025_Q4_Dic_S\d+$/);
  });

  it('should add printing-report class to body', () => {
    handlePrintReport(reportContentRef, baseReportData, 'es');

    expect(document.body.classList.contains('printing-report')).toBe(true);
  });

  it('should clean up after timeout fallback', () => {
    vi.useFakeTimers();

    handlePrintReport(reportContentRef, baseReportData, 'es');
    expect(document.body.classList.contains('printing-report')).toBe(true);

    vi.advanceTimersByTime(1000);
    expect(document.body.classList.contains('printing-report')).toBe(false);
    expect(printContainer.childNodes.length).toBe(0);
    expect(document.title).toBe(originalTitle);

    vi.useRealTimers();
  });

  it('should clean up via afterprint event', () => {
    handlePrintReport(reportContentRef, baseReportData, 'es');
    expect(document.body.classList.contains('printing-report')).toBe(true);

    window.dispatchEvent(new Event('afterprint'));
    expect(document.body.classList.contains('printing-report')).toBe(false);
    expect(printContainer.childNodes.length).toBe(0);
    expect(document.title).toBe(originalTitle);
  });

  it('should create print container if not pre-existing in DOM', () => {
    // Remove the pre-created container to exercise createElement path
    printContainer.remove();

    handlePrintReport(reportContentRef, baseReportData, 'es');

    const created = document.getElementById('print-container');
    expect(created).not.toBeNull();
    expect(created?.querySelector('.print-branding')).not.toBeNull();

    // Cleanup the dynamically created container
    created?.remove();
  });

  it('should populate footer meta with date, time, and transaction count', () => {
    handlePrintReport(reportContentRef, baseReportData, 'es');

    const meta = printContainer.querySelector('.print-footer-meta');
    expect(meta).not.toBeNull();
    // Meta format: "date, time · Basado en X transacciones"
    expect(meta?.textContent).toMatch(/·\s*Basado en 42 transacciones$/);
  });

  it('should format footer meta with English locale when lang is en', () => {
    handlePrintReport(reportContentRef, baseReportData, 'en');

    const meta = printContainer.querySelector('.print-footer-meta');
    expect(meta).not.toBeNull();
    expect(meta?.textContent).toMatch(/·\s*Based on 42 transactions$/);
  });

  it('should not double-cleanup when both afterprint and timeout fire', () => {
    vi.useFakeTimers();

    handlePrintReport(reportContentRef, baseReportData, 'es');
    expect(document.body.classList.contains('printing-report')).toBe(true);

    // First cleanup via afterprint
    window.dispatchEvent(new Event('afterprint'));
    expect(document.body.classList.contains('printing-report')).toBe(false);
    expect(printContainer.childNodes.length).toBe(0);

    // Repopulate container to verify timeout doesn't clear it again
    const marker = document.createElement('div');
    marker.id = 'double-cleanup-marker';
    printContainer.appendChild(marker);

    // Second cleanup via timeout — should be guarded by `cleaned` flag
    vi.advanceTimersByTime(1000);
    expect(document.getElementById('double-cleanup-marker')).not.toBeNull();

    marker.remove();
    vi.useRealTimers();
  });
});

describe('generatePdfFilename', () => {
  it('should generate weekly filename with quarter, month, and week', () => {
    const result = generatePdfFilename('weekly', {
      start: new Date(2025, 11, 2),
      end: new Date(2025, 11, 8),
    });
    expect(result).toMatch(/^Gastify_report_2025_Q4_Dic_S\d+$/);
  });

  it('should generate monthly filename with quarter and month', () => {
    const result = generatePdfFilename('monthly', {
      start: new Date(2025, 5, 1),
      end: new Date(2025, 5, 30),
    });
    expect(result).toBe('Gastify_report_2025_Q2_Jun');
  });

  it('should generate quarterly filename with quarter only', () => {
    const result = generatePdfFilename('quarterly', {
      start: new Date(2025, 0, 1),
      end: new Date(2025, 2, 31),
    });
    expect(result).toBe('Gastify_report_2025_Q1');
  });

  it('should generate yearly filename with year only', () => {
    const result = generatePdfFilename('yearly', {
      start: new Date(2025, 0, 1),
      end: new Date(2025, 11, 31),
    });
    expect(result).toBe('Gastify_report_2025');
  });

  it('should fall back to yearly format for unknown period type', () => {
    const result = generatePdfFilename('custom' as never, {
      start: new Date(2025, 3, 1),
      end: new Date(2025, 3, 30),
    });
    expect(result).toBe('Gastify_report_2025');
  });
});
