name: atlas-sync-observations
description: "Manually process observations and update instincts"
author: "BMad + Atlas"

# Atlas Integration
atlas_features:
  learning_system: true        # Continuous learning integration

atlas_knowledge_fragments:
  required: []
  optional:
    - "10-instincts.md"       # For reference

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Atlas memory paths
atlas_memory: "{project-root}/_bmad/agents/atlas/atlas-sidecar"
atlas_learning: "{atlas_memory}/learning"

# Learning system paths
learning_config: "{atlas_learning}/config.json"
observations_file: "{atlas_learning}/observations.jsonl"
instincts_file: "{atlas_learning}/instincts.json"
evaluator_script: "{project-root}/_bmad/agents/atlas/hooks/evaluate-session.cjs"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/atlas-sync-observations"
instructions: "{installed_path}/instructions.md"

standalone: true
