name: atlas-evolve
description: "Promote high-confidence instincts to permanent knowledge fragments"
author: "BMad + Atlas"

# Atlas Integration
atlas_features:
  learning_system: true        # Continuous learning integration
  memory_feeding: true         # Updates knowledge fragments

atlas_knowledge_fragments:
  required:
    - "10-instincts.md"       # Target for evolved patterns
  optional:
    - "06-lessons.md"         # For cross-referencing lessons

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Atlas memory paths
atlas_memory: "{project-root}/_bmad/agents/atlas/atlas-sidecar"
atlas_index: "{atlas_memory}/atlas-index.csv"
atlas_knowledge: "{atlas_memory}/knowledge"
atlas_learning: "{atlas_memory}/learning"

# Learning system paths
learning_config: "{atlas_learning}/config.json"
instincts_file: "{atlas_learning}/instincts.json"
instincts_fragment: "{atlas_knowledge}/10-instincts.md"
sync_history: "{atlas_knowledge}/09-sync-history.md"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/atlas-evolve"
instructions: "{installed_path}/instructions.md"

standalone: true
