# ECC-Enhanced Story Creation Workflow
name: ecc-create-story
description: "Story creation using ECC agents orchestrated by ECC Orchestrator - Planner + Architect for technical analysis"
author: "BMad"

# ECC Integration - Orchestrator Configuration
ecc_orchestration:
  enabled: true
  orchestrator: "ECC Orchestrator"

  # ECC agents used in this workflow
  agents:
    planner:
      subagent_type: "everything-claude-code:planner"
      purpose: "Analyze requirements, identify risks, plan implementation approach"
    architect:
      subagent_type: "everything-claude-code:architect"
      purpose: "Technical design, pattern recommendations, dependency analysis"

  # Sequential with parallel option
  sequence: "planner → architect → (parallel: database-reviewer + security-reviewer if needed)"

  # Optional parallel technical review
  parallel_phases:
    technical_review:
      agents: ["database-reviewer", "security-reviewer"]
      condition: "story involves database or auth"
      description: "Parallel technical review for complex stories"

# Project Knowledge Integration (replaces Atlas - migrated 2026-02-05)
project_knowledge:
  enabled: true
  load_at_session_start: true
  files:
    required:
      - "{project-root}/_bmad/bmm/knowledge/code-review-patterns.md"
      - "{project-root}/docs/architecture/TESTING-GUIDELINES.md"
      - "{project-root}/docs/architecture/firestore-patterns.md"
    optional:
      - "{project-root}/docs/architecture/state-management.md"
      - "{project-root}/docs/architecture/component-patterns.md"

# Story Sizing Guidelines (Opus 4.6 - Updated 2026-02-05)
sizing_guidelines:
  model: "Opus 4.6"
  updated: "2026-02-05"
  small: { tasks: "1-3", subtasks: "≤10", files: "≤4", points: "1-2" }
  medium: { tasks: "3-6", subtasks: "≤25", files: "≤8", points: "3-5" }
  large: { tasks: "6-8", subtasks: "≤40", files: "≤12", points: "5-8" }
  too_large: { tasks: ">8", subtasks: ">40", files: ">12", action: "split" }
  principles:
    - "Prefer fewer larger stories over many micro-stories"
    - "Group related layers (types→service→UI→tests) into single stories"
    - "Include E2E tests in the story they verify"
    - "Foundation + integration can be ONE story if within limits"

# E2E Testing Integration
e2e_testing:
  enabled: true
  conventions_paths:
    - "tests/e2e/E2E-TEST-CONVENTIONS.md"
    - "tests/e2e/README.md"
    - "docs/testing/e2e-conventions.md"
    - "docs/E2E-TESTING.md"
  check_existing_coverage: true
  prefer_extending_existing: true  # Prefer extending existing E2E tests over creating new ones
  actions:
    - "verify_existing"   # Existing test covers feature
    - "extend_existing"   # Extend existing test (PREFERRED for critical paths)
    - "create_new"        # Create new test (only if no existing test can cover)

# Project knowledge paths (replaces Atlas memory - migrated 2026-02-05)
project_knowledge_path: "{project-root}/_bmad/bmm/knowledge"
project_architecture_path: "{project-root}/docs/architecture"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
story_dir: "{config_source}:sprint_artifacts"
date: system-generated

sprint_artifacts: "{config_source}:sprint_artifacts"
sprint_status: "{sprint_artifacts}/sprint-status.yaml || {output_folder}/sprint-status.yaml"
epics_dir: "{output_folder}"

# Knowledge cache files
knowledge_cache_files:
  - "_bmad/bmm/knowledge/code-review-patterns.md"
  - "docs/architecture/TESTING-GUIDELINES.md"
  - "docs/architecture/firestore-patterns.md"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/ecc-create-story"
instructions: "{installed_path}/instructions.xml"

standalone: true
